### PR TITLE
Linux

### PR DESCRIPTION
**Pull request by adam-becker**
Following the comment left in #10, I didn't have `fsce` locally, and I didn't feel like installing it/making a container that had it.

Feel free to tell me if more needs to be done.

### CODE REVIEW

**Comment by georgewfraser** [comment]
You can install vsce by doing `npm install -g vsce`. I'm not using linux so it would be helpful if you would just test that this actually works by building it locally.

**Comment by adam-becker** [comment]
I changed a few more things. After installing the VSIX it was still loading the OSx version, so I got that all resolved. However I see this in the `F# Language Server` output:

```
[Error - 1:28:07 PM] Connection to server is erroring. Shutting down server.
[Error - 1:28:07 PM] Connection to server is erroring. Shutting down server.
```

Any steps I can do to debug?

**Comment by adam-becker** [comment]
Any thoughts? I can't find any reason why `FSharp.Core.dll` and `System.ComponentModel.Composition.dll` would be missing on my system. I have `fsharp`, `dotnet-2.1-sdk` and even `mono-complete` installed.

I'm also not sure why there are separate self contained deployments for various OSes, it seems to me that if you're doing the kind of work where you'd need `fsharp-language-server` you more than likely have dotnet installed.

**Comment by georgewfraser** [comment]
You're seeing this message right here: 

https://github.com/georgewfraser/fsharp-language-server/blob/master/src/FSharpLanguageServer/ProjectManager.fs#L233

That's a warning, not an error. You may have trouble with .fsx files but the language server should still work. If it's crashing, the problem must be something else.

The reason why it's packaged standalone is so it doesn't depend on what version of dotnet you have installed.

**Comment by adam-becker** [comment]
@gubser Maybe I missed a step when compiling/packaging/installing, can you give me a quick run down of what steps you took?

Here's what I did:

1. Run `$ ./scripts/build.sh` from the project root directory.
2. Open VSCode and `CTRL+SHIFT+P` then select `Extensions: Install from VSIX...`
3. Navigate to `build.vsix`.
4. Reload VSCode and open a new F# .NET Core project. (`dotnet new console --language F# -o TestProject`)

**Comment by gubser** [comment]
I did the same but I needed to uninstall the extension before installing from VSIX.
I'm not sure if it matters, but I've also installed the C# extension.

**Comment by adam-becker** [comment]
@gubser If you run the install script I added (`./scripts/install.sh`) do you still get a working language server?

@georgewfraser Any tips on how to properly debug this issue?

I'll step through tonight in a debugger and see what is causing the errors.. Although that message appears to be coming from VSCode, so it might just be that the protocol isn't working perfectly in some weird edge case, at which point I'd have no idea how to trace this down.

**Comment by gubser** [comment]
1. Uninstalled F# Language Server
2. Run `./scripts/install.sh`
3. Go to Extension tab, click "Reload" button in the "F# Language Server"-entry
Works fine :+1:

**Comment by adam-becker** [comment]
@georgewfraser I'm still unable to run the language server, this is not production ready for me. I never got a response to my question of "How can I debug this properly?" either.

**Pull request merged**
