### PR TITLE
Adding Linux support.

### LINKED ISSUE #10: Ubuntu support
I tried running the VS Code extension while on Ubuntu, but it failed with the following message:

```
[Error - 2:01:11 PM] Connection to server is erroring. Shutting down server.
[Error - 2:01:11 PM] Connection to server is erroring. Shutting down server.
/home/nat/.vscode/extensions/georgewfraser.fsharp-language-server-0.1.9/src/FSharpLanguageServer/bin/Release/netcoreapp2.0/osx.10.11-x64/publish/FSharpLanguageServer: 1: /home/nat/.vscode/extensions/georgewfraser.fsharp-language-server-0.1.9/src/FSharpLanguageServer/bin/Release/netcoreapp2.0/osx.10.11-x64/publish/FSharpLanguageServer: Syntax error: word unexpected (expecting ")")
```

Is this failing because I'm using Ubuntu instead of OS X?

### PR DESCRIPTION
**Pull request by NatElkins**
I think this is all that needs to be done for this.  Fixes #10.  Let me know if there's anything else.

### CODE REVIEW

**Comment by georgewfraser** [comment]
Have you tested it?

**Comment by NatElkins** [comment]
ha, Uh, no, but not for lack of trying!  I couldn't figure out how to get the whole thing building with your custom fork of FSharp.Compiler.Services.

**Comment by georgewfraser** [comment]
Oh, I should really have that on a branch, it's a work-in-progress. One second...

**Comment by georgewfraser** [comment]
OK, I have rolled back master and it should now build out-of-the-box. Could you rebase your change and check that it works?

**Pull request closed without merging**
